### ISSUE TITLE
Issue on Raspberry pi

### ISSUE THREAD

**Issue by Pllet** [moonbuggy/docker-medusa#1]
Hi, i tried to make it work on raspberry pi 4b on raspbian, but got this.

s6-rc-compile: fatal: during dependency resolution for service medusa: undefined service name add-contenv

Any help is welcome, thanks.

**Comment by moonbuggy** [comment]
There was an issue with an upstream base image's init system, and I found a bonus bug in my build system along the way.

Thanks for drawing my attention to this. Leaving either problem unnoticed would have been increasingly annoying for me as they propagated over time. 

I've just pushed fresh images and can confirm the error is resolved on one of my ARMv7 devices. I expect pulling a fresh image should resolve it for you as well.
